version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Update pip
          command: pip install --user --upgrade pip
      - run:
          name: Install packages
          command: pip install --user .
      - run:
          name: Run tests
          command: pytest


workflows:
  main:
    jobs:
      - build