version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Update pip
          command: pip install --user --upgrade pip
      - run:
          name: Install package
          command: pip install --user .
      - run:
          name: Test
          command: pytest

workflows:
  main:
    jobs:
      - build